// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmeAccounting.Persistence;

#nullable disable

namespace SmeAccounting.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmeAccounting.Domain.Entities.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateOnly>("PostingDate")
                        .HasColumnType("date")
                        .HasColumnName("posting_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("VoucherNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("voucher_no");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "PostingDate")
                        .HasDatabaseName("ix_gl_entries_company_posting");

                    b.HasIndex("CompanyId", "VoucherNo")
                        .IsUnique()
                        .HasDatabaseName("ux_gl_entries_company_voucher");

                    b.ToTable("journal_entries", "gl");
                });

            modelBuilder.Entity("SmeAccounting.Domain.Entities.JournalEntry", b =>
                {
                    b.OwnsMany("SmeAccounting.Domain.Entities.JournalLine", "Lines", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("AccountCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("account_code");

                            b1.Property<string>("Description")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("description");

                            b1.Property<Guid>("EntryId")
                                .HasColumnType("uuid")
                                .HasColumnName("entry_id");

                            b1.HasKey("Id");

                            b1.HasIndex("EntryId");

                            b1.ToTable("journal_lines", "gl");

                            b1.WithOwner()
                                .HasForeignKey("EntryId");

                            b1.OwnsOne("SmeAccounting.Domain.ValueObjects.Money", "Credit", b2 =>
                                {
                                    b2.Property<int>("JournalLineId")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(19,4)")
                                        .HasColumnName("credit_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("credit_currency");

                                    b2.HasKey("JournalLineId");

                                    b2.ToTable("journal_lines", "gl");

                                    b2.WithOwner()
                                        .HasForeignKey("JournalLineId");
                                });

                            b1.OwnsOne("SmeAccounting.Domain.ValueObjects.Money", "Debit", b2 =>
                                {
                                    b2.Property<int>("JournalLineId")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(19,4)")
                                        .HasColumnName("debit_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("debit_currency");

                                    b2.HasKey("JournalLineId");

                                    b2.ToTable("journal_lines", "gl");

                                    b2.WithOwner()
                                        .HasForeignKey("JournalLineId");
                                });

                            b1.Navigation("Credit")
                                .IsRequired();

                            b1.Navigation("Debit")
                                .IsRequired();
                        });

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
